### ISSUE TITLE
_config.yaml read too often

### ISSUE THREAD

**Issue by paddy-hack** [skatkov/jekyll-heroicons#11]
As soon as I started using this plugin, I started seeing oodles of
``` console
Configuration file: /home/zway/src/kata/code/_config.yaml
```
when I change a single Markdown file while `jekyll serve` is running.

Some digging leads me to believe that `Jekyll::Heroicons#config` is invoked for every use of `{% heroicon ...%}`.  That seems like overkill.

I *think* that instead of `@config`, an instance variable, you should be using `@@config`, a class variable, so that the configuration is only read once.

Note that `jekyll serve` needs a restart when changing `_config.yaml` anyway.

**Comment by skatkov** [comment]
@paddy-hack thank you for reporting this issue and such a thorough investigation.

I was able to reproduce this on two of my projects as well. Small, but very annoying issue.

Rubygems should already have 0.4.1 release with this issue resolved.
